# Generated by Django 3.1.2 on 2020-10-17 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(choices=[('ns', 'North Sea'), ('wa', 'West Africa'), ('as', 'Asia'), ('oc', 'Oceania'), ('gm', 'Gulf of Mexico'), ('br', 'Brazil')], default='br', help_text=' Location of the Equipment', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('status', models.CharField(choices=[('A', 'ACTIVE'), ('I', 'INACTIVE')], default='A', help_text='Equipment status', max_length=1)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_manager.equipment')),
            ],
            options={
                'ordering': ['equipment__vessel', 'equipment__name', 'code', 'equipment__location', 'status'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_manager.vessel'),
        ),
    ]
