# Generated by Django 3.1.2 on 2020-10-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['vessel', 'name', 'code', 'location', 'status']},
        ),
        migrations.AddField(
            model_name='equipment',
            name='code',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('A', 'ACTIVE'), ('I', 'INACTIVE')], default='A', help_text='Equipment status', max_length=1),
        ),
        migrations.DeleteModel(
            name='EquipmentInstance',
        ),
    ]
