# Generated by Django 3.1.2 on 2020-10-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_manager', '0002_auto_20201017_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.CharField(default='Brazil', help_text=' Location of the Equipment', max_length=20),
        ),
    ]
