# Generated by Django 3.1.2 on 2020-10-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_manager', '0003_auto_20201017_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.BooleanField(default=True, help_text='Equipment status'),
        ),
    ]
